apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ .Values.image }}
          args:
            - /bin/sh
            - -c
            - 'battery-email-api -token $TOKEN -from $FROM -smtp-host $SMTP_HOST -user $USER -password $PASSWORD {{ if ne .Values.dbDriver "none"}}-db-driver $DB_DRIVER -db-connection "$DB_CONNECTION"{{end}}'
          env:
            - name: TOKEN
              value: {{ required "token" .Values.token }}
            - name: FROM
              value: {{ required "emailFrom" .Values.emailFrom }}
            - name: SMTP_HOST
              value: {{ required "emailSmtpHost" .Values.emailSmtpHost }}
            - name: USER
              value: {{ required "emailUser" .Values.emailUser }}
            - name: PASSWORD
              value: {{ required "emailPassword" .Values.emailPassword }}
            - name: DB_DRIVER
              value: {{ .Values.dbDriver }}
            - name: DB_CONNECTION
              value: {{ .Values.dbConnection }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
              - name: Host
                value: {{ .Values.host }}
